import { ComponentFixture, TestBed } from '@angular/core/testing';

import { AutogeneratedRidesUpdate } from './autogenerated-rides-update';

describe('AutogeneratedRidesUpdate', () => {
  let component: AutogeneratedRidesUpdate;
  let fixture: ComponentFixture<AutogeneratedRidesUpdate>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [AutogeneratedRidesUpdate],
    }).compileComponents();

    fixture = TestBed.createComponent(AutogeneratedRidesUpdate);
    component = fixture.componentInstance;
    await fixture.whenStable();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
