
import { Component, OnInit } from '@angular/core'
import { CommonModule } from '@angular/common'
import { FormsModule } from '@angular/forms'
import { Ride } from '../../services/ride'      // apna path
import { Snackbar } from '../../services/snackbar'     // apna path
import { AuthHelper } from '../../helpers/auth-helper'
import { AuthService } from '../../services/auth'

interface AutoRide {
  _id: string
  start_location: { name: string }
  end_location: { name: string }
  departure_time: string
  available_seats: number
  price_per_seat: number
  route_via: string
  status: string
  // edit state
  editDate?: string
  editTime?: string
  editSeats?: number
  editPrice?: number
  editRouteId?: string
  saving?: boolean
}

@Component({
  selector: 'app-autogenerated-rides-update',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './autogenerated-rides-update.html',
  styleUrls: ['./autogenerated-rides-update.css'],
})
export class AutogeneratedRidesUpdate implements OnInit {
  rides: AutoRide[] = []
  isLoading = false
  notAllowed = false
  userId = ''

  readonly routeOptions = [
    { id: 'r1',  from: 'gurgaon',    to: 'saharanpur', via: 'UER2 · Sonipat · Baghpat · Shamli',              basePrice: 440, distance: 220, label: 'Via Baghpat' },
    { id: 'r2',  from: 'gurgaon',    to: 'saharanpur', via: 'UER2 · Sonipat · Panipat · Shamli',              basePrice: 460, distance: 220, label: 'Via Panipat' },
    { id: 'r3',  from: 'gurgaon',    to: 'saharanpur', via: 'UER2 · Kundali · Delhi-Dehradun Expressway',     basePrice: 500, distance: 220, label: 'Via Kundali Expressway' },
    { id: 'r4',  from: 'gurgaon',    to: 'saharanpur', via: 'Dhaula Kuan · Delhi-Dehradun Expressway · UER2', basePrice: 480, distance: 210, label: 'Via Dhaula Kuan' },
    { id: 'r1r', from: 'saharanpur', to: 'gurgaon',    via: 'Shamli · Baghpat · Sonipat · UER2',              basePrice: 440, distance: 220, label: 'Via Baghpat' },
    { id: 'r2r', from: 'saharanpur', to: 'gurgaon',    via: 'Shamli · Panipat · Sonipat · UER2',              basePrice: 460, distance: 220, label: 'Via Panipat' },
    { id: 'r3r', from: 'saharanpur', to: 'gurgaon',    via: 'Delhi-Dehradun Expressway · Kundali · UER2',     basePrice: 500, distance: 220, label: 'Via Kundali Expressway' },
    { id: 'r4r', from: 'saharanpur', to: 'gurgaon',    via: 'UER2 · Delhi-Dehradun Expressway · Dhaula Kuan', basePrice: 480, distance: 210, label: 'Via Dhaula Kuan' },
  ]

  constructor(
    private rideService: Ride,
    private authService:AuthService,
    private snackbar: Snackbar
  ) {}

 ngOnInit(): void {
  const token = AuthHelper.getToken()

  if (!token) {
    this.notAllowed = true
    this.isLoading = false
    this.snackbar.error('Please login again')
    return
  }

  // ✅ API se pura user object lo
  this.authService.getCurrentUser().subscribe({
    next: (res: any) => {
      const user = res
      console.log(user)  // ya res.data ya res — apna response structure dekho

      if (!['rider', 'both'].includes(user.role)) {
        this.notAllowed = true
        this.isLoading = false
        return
      }

      this.userId = user.Id 
      console.log(this.userId) // ✅ userId set hoga ab
      this.loadRides()
    },
    error: () => {
      this.notAllowed = true
      this.isLoading = false
      this.snackbar.error('Session expired, please login again')
    }
  })
}

  loadRides(): void {
  this.isLoading = true
  this.rideService.getAutogeneratedRides(this.userId).subscribe({
    next: (res: any) => {
      this.rides = (res.rides || [])
        .filter((r: AutoRide) => !['completed', 'cancelled'].includes(r.status))  // ✅
        .map((r: AutoRide) => this.initEditState(r))
      this.isLoading = false
    },
    error: (err: any) => {
      this.isLoading = false
      if (err?.status === 403) this.notAllowed = true
      this.snackbar.error(err?.error?.message || 'Could not load auto-generated rides')
    },
  })
}

  private initEditState(r: AutoRide): AutoRide {
    const iso = r.departure_time              // "2026-06-05T09:00:00.000Z"
    r.editDate = iso.slice(0, 10)             // "2026-06-05"
    r.editTime = iso.slice(11, 16)            // "09:00"
    r.editSeats = r.available_seats
    r.editPrice = r.price_per_seat

    const match = this.routesFor(r).find((o) => o.via === r.route_via)
    r.editRouteId = match?.id || ''
    return r
  }

  routesFor(r: AutoRide) {
    const from = (r.start_location?.name || '').toLowerCase()
    const to = (r.end_location?.name || '').toLowerCase()
    return this.routeOptions.filter(
      (o) => from.includes(o.from) && to.includes(o.to)
    )
  }

  onRouteChange(r: AutoRide): void {
    const opt = this.routeOptions.find((o) => o.id === r.editRouteId)
    if (opt) r.editPrice = opt.basePrice
  }

  selectedRoute(r: AutoRide) {
    return this.routeOptions.find((o) => o.id === r.editRouteId)
  }

  // Display ke liye — "Friday, 5 Jun 2026"
  displayDate(r: AutoRide): string {
    if (!r.editDate) return ''
    const d = new Date(r.editDate + 'T00:00:00')
    return d.toLocaleDateString('en-IN', {
      weekday: 'long', day: 'numeric', month: 'short', year: 'numeric',
    })
  }

  saveRide(r: AutoRide): void {
    const opt = this.selectedRoute(r)
    if (!opt) {
      this.snackbar.error('Please select a route')
      return
    }
    if (!r.editDate || !r.editTime) {
      this.snackbar.error('Please select date and time')
      return
    }
    if (!r.editSeats || r.editSeats < 1 || r.editSeats > 8) {
      this.snackbar.error('Seats must be between 1 and 8')
      return
    }
    if (!r.editPrice || r.editPrice < 1) {
      this.snackbar.error('Please enter a valid price')
      return
    }

    // IST-as-UTC — jo select kiya wahi DB mein store hoga
    const departureIso = `${r.editDate}T${r.editTime}:00.000Z`

    r.saving = true
    this.rideService.updateAutogeneratedRide({
      rideId: r._id,
      userId: this.userId,
      departure_time: departureIso,
      available_seats: Number(r.editSeats),
      price_per_seat: Number(r.editPrice),
      route_via: opt.via,
    }).subscribe({
      next: () => {
        r.saving = false
        this.snackbar.success('Ride updated successfully')
        this.loadRides()
      },
      error: (err: any) => {
        r.saving = false
        this.snackbar.error(err?.error?.message || 'Update failed')
      },
    })
  }
}